// <auto-generated />
using System;
using AccesoDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260915215007_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id_alquiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteDNI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DNI")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPagar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_alquiler");

                    b.HasIndex("ClienteDNI");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("AccesoDatos.Models.Cliente", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicenciaConducir")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DNI");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AccesoDatos.Models.DetalleAlquiler", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlquilerId_alquiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_alquiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Patente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioPorDia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subtotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculoPatente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_detalle");

                    b.HasIndex("AlquilerId_alquiler");

                    b.HasIndex("VehiculoPatente");

                    b.ToTable("DetalleAlquileres");
                });

            modelBuilder.Entity("AccesoDatos.Models.Vehículo", b =>
                {
                    b.Property<int>("Patente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrecioPorDia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Patente");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.HasOne("AccesoDatos.Models.Cliente", "Cliente")
                        .WithMany("Alquileres")
                        .HasForeignKey("ClienteDNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AccesoDatos.Models.DetalleAlquiler", b =>
                {
                    b.HasOne("AccesoDatos.Models.Alquiler", "Alquiler")
                        .WithMany("Detalles")
                        .HasForeignKey("AlquilerId_alquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Models.Vehículo", "Vehiculo")
                        .WithMany("DetalleAlquileres")
                        .HasForeignKey("VehiculoPatente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AccesoDatos.Models.Cliente", b =>
                {
                    b.Navigation("Alquileres");
                });

            modelBuilder.Entity("AccesoDatos.Models.Vehículo", b =>
                {
                    b.Navigation("DetalleAlquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
